This is makeindex, version 2.16 [MiKTeX 22.12].
Scanning style file ./Dissertacao_MPEPR_Renan_Lima.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Dissertacao_MPEPR_Renan_Lima.acn....done (152 entries accepted, 0 rejected).
Sorting entries....done (1332 comparisons).
Generating output file Dissertacao_MPEPR_Renan_Lima.acr....done (89 lines written, 0 warnings).
Output written in Dissertacao_MPEPR_Renan_Lima.acr.
Transcript written in Dissertacao_MPEPR_Renan_Lima.alg.
